<?php

/**
 * @package siteconfig
 * @subpackage tests
 */
class SiteConfigTest extends SapphireTest
{
    protected static $fixture_file = 'SiteConfigTest.yml';

    protected $illegalExtensions = array(
        'SilverStripe\\CMS\\Model\\SiteTree' => array('SiteTreeSubsites')
    );

    public function setUpOnce()
    {
        // Fix issue with tests failing without CMS module
        if (!class_exists('SilverStripe\\CMS\\Model\\SiteTree')) {
            unset($this->illegalExtensions['SilverStripe\\CMS\\Model\\SiteTree']);
        }

        parent::setUpOnce(); // TODO: Change the autogenerated stub
    }

    public function testCanCreateRootPages()
    {
        $config = $this->objFromFixture('SiteConfig', 'default');

        // Log in without pages admin access
        $this->logInWithPermission('CMS_ACCESS_AssetAdmin');
        $this->assertFalse($config->canCreateTopLevel());

        // Login with necessary edit permission
        $perms = SiteConfig::config()->required_permission;
        $this->logInWithPermission(reset($perms));
        $this->assertTrue($config->canCreateTopLevel());
    }

    public function testCanViewPages()
    {
        $config = $this->objFromFixture('SiteConfig', 'default');
        $this->assertTrue($config->canViewPages());
    }

    public function testCanEdit()
    {
        $config = $this->objFromFixture('SiteConfig', 'default');

        // Unrelated permissions don't allow siteconfig
        $this->logInWithPermission('CMS_ACCESS_AssetAdmin');
        $this->assertFalse($config->canEdit());

        // Only those with edit permission can do this
        $this->logInWithPermission('EDIT_SITECONFIG');
        $this->assertTrue($config->canEdit());
    }

    public function testCanEditPages()
    {
        $config = $this->objFromFixture('SiteConfig', 'default');

        // Log in without pages admin access
        $this->logInWithPermission('CMS_ACCESS_AssetAdmin');
        $this->assertFalse($config->canEditPages());

        // Login with necessary edit permission
        $perms = SiteConfig::config()->required_permission;
        $this->logInWithPermission(reset($perms));
        $this->assertTrue($config->canEditPages());
    }
}
